apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-public-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-public-frontend
  template:
    metadata:
      labels:
        app: lms-public-frontend
    spec:
      containers:
        - name: lms-public-frontend-container-label
          image: dlacrtmp.azurecr.io/lms-public-frontend:2.0.0
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://20.204.207.156/api"
